In [1]:
import pd

ImportError: No module named pd

In [3]:
import os
import math
import numpy as np 

import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline
plt.style.use('ggplot')

In [20]:
df = pd.read_csv(os.path.join('shelter-animal-outcomes.csv.gz'), index_col = 'AnimalID')

In [9]:
df

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White
3,A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream
4,A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan
5,A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,Intact Female,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan
6,A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Tabby
7,A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Brown Tabby
8,A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,Spayed Female,5 months,American Pit Bull Terrier Mix,Red/White
9,A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,Spayed Female,1 year,Cairn Terrier,White
10,A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Black
11,A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,Spayed Female,2 years,Miniature Schnauzer Mix,Silver
12,A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,Neutered Male,4 years,Pit Bull Mix,Brown
13,A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,Neutered Male,2 years,Yorkshire Terrier Mix,Black/Red
14,A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Great Pyrenees Mix,White/Cream
15,A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Orange Tabby/White
16,A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby
17,A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,Intact Female,2 weeks,Pit Bull Mix,Brown/White
18,A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,Intact Female,2 years,Angora Mix,White
19,A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Flat Coat Retriever Mix,Black
20,A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,Intact Male,2 months,Queensland Heeler Mix,Black/White
21,A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,Spayed Female,1 year,Domestic Shorthair Mix,White
22,A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,Spayed Female,2 years,Plott Hound/Boxer,Brown Brindle/White
23,A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,Neutered Male,10 months,German Shepherd Mix,Brown/White
24,A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,Neutered Male,2 months,German Shepherd Mix,Black/Brown
25,A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,Intact Female,1 month,Domestic Shorthair Mix,Orange Tabby
26,A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,Spayed Female,6 months,American Staffordshire Terrier Mix,Chocolate/White
27,A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,Spayed Female,5 years,Chihuahua Shorthair Mix,White/Tan
28,A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Cream Tabby/White
29,A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,Neutered Male,7 years,Russian Blue Mix,Blue
...,...,...,...,...,...,...,...,...,...,...
26699,A676460,Mario,2014-04-21 14:01:00,Euthanasia,Behavior,Dog,Neutered Male,2 years,American Pit Bull Terrier Mix,White/Black
26700,A704999,Lion,2015-06-15 19:28:00,Return_to_owner,NaN,Dog,Intact Male,10 months,Great Pyrenees/Anatol Shepherd,Tan/Cream
26701,A678842,Ella,2014-06-15 17:41:00,Transfer,Partner,Dog,Intact Female,11 months,Jack Russell Terrier Mix,White/Black
26702,A713637,NaN,2015-10-11 09:42:00,Died,In Kennel,Cat,Spayed Female,2 years,Siamese Mix,Lynx Point
26703,A716670,Mowmow,2015-12-04 12:22:00,Transfer,Partner,Cat,Neutered Male,6 years,Domestic Longhair Mix,Seal Point
26704,A716223,Alice,2015-11-17 17:17:00,Transfer,Partner,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,White/Black
26705,A662498,Grace,2013-10-19 15:34:00,Transfer,Partner,Cat,Intact Female,2 months,Domestic Shorthair Mix,Tortie
26706,A689942,Zoey,2014-10-19 13:29:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Black
26707,A682690,NaN,2014-07-01 17:06:00,Euthanasia,Suffering,Cat,Unknown,1 year,Domestic Shorthair Mix,Brown Tabby
26708,A666920,Herbie,2013-11-13 17:32:00,Transfer,Partner,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,White/Brown
26709,A714386,NaN,2015-10-24 00:00:00,Adoption,NaN,Dog,Spayed Female,1 month,Chihuahua Shorthair Mix,Sable/Buff
26710,A692622,Bonnie,2014-11-24 17:21:00,Transfer,Partner,Dog,Intact Female,1 month,Chihuahua Shorthair/Yorkshire Terrier,Brown/Black
26711,A666284,Sonja,2013-10-30 18:32:00,Transfer,Partner,Dog,Intact Female,1 year,Cocker Spaniel/Dachshund,Buff
26712,A535277,Merlin,2015-04-20 16:04:00,Return_to_owner,NaN,Dog,Neutered Male,12 years,Rat Terrier,Chocolate/Tan
26713,A671169,NaN,2014-01-20 17:37:00,Euthanasia,Suffering,Cat,Intact Female,18 years,Domestic Longhair Mix,Tortie
26714,A679031,Pete,2014-05-31 16:11:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Orange Tabby
26715,A708833,Luna,2015-08-05 17:03:00,Adoption,NaN,Dog,Spayed Female,2 months,Pointer Mix,Black/White
26716,A697158,Max,2015-05-02 21:04:00,Adoption,Offsite,Dog,Neutered Male,2 months,Newfoundland Mix,White/Black
26717,A519949,Bella,2014-06-30 17:34:00,Return_to_owner,NaN,Dog,Spayed Female,9 years,Bullmastiff Mix,Black
26718,A701044,NaN,2015-04-28 14:26:00,Adoption,NaN,Dog,Neutered Male,2 months,Siberian Husky/German Shepherd,Black/Tricolor
26719,A707871,NaN,2015-07-20 09:00:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Brown Tabby/White
26720,A704405,Brownie,2015-07-18 14:08:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Brown Tabby
26721,A662019,Green Bean,2014-07-17 09:43:00,Adoption,Foster,Cat,Spayed Female,5 years,Domestic Shorthair Mix,Black
26722,A687056,NaN,2014-08-31 09:00:00,Transfer,SCRP,Cat,Intact Male,5 months,Domestic Shorthair Mix,Orange Tabby
26723,A716997,Zeus,2016-01-29 18:52:00,Adoption,NaN,Dog,Neutered Male,6 years,Staffordshire Mix,Blue/White
26724,A702446,NaN,2015-05-14 11:56:00,Transfer,Partner,Cat,Intact Male,1 month,Domestic Shorthair Mix,Brown Tabby/White
26725,A718934,NaN,2016-01-20 18:59:00,Transfer,SCRP,Cat,Spayed Female,3 months,Domestic Shorthair Mix,Brown Tabby
26726,A698128,Zeus,2015-03-09 13:33:00,Adoption,NaN,Dog,Neutered Male,4 years,Old English Bulldog Mix,White/Tan
26727,A677478,NaN,2014-04-27 12:22:00,Transfer,Partner,Cat,Intact Male,4 weeks,Domestic Shorthair Mix,Black
26728,A706629,NaN,2015-07-02 09:00:00,Transfer,SCRP,Cat,Intact Male,1 year,Domestic Shorthair Mix,Brown Tabby/White

In [10]:
df.shape

(26729, 10)

In [13]:
df[df.Breed == "Pit Bull Mix"].shape

(1906, 10)

In [16]:
df.describe()

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
count,26729,19038,26729,26729,13117,26729,26728,26711,26729,26729
unique,26729,6374,22918,5,16,2,5,44,1380,366
top,A705677,Max,2015-08-11 00:00:00,Adoption,Partner,Dog,Neutered Male,1 year,Domestic Shorthair Mix,Black/White
freq,1,136,19,10769,7816,15595,9779,3969,8810,2824

In [19]:
df.AnimalID.shape

(26729,)

In [22]:
df.Name.value_counts()

Max            136
Bella          135
Charlie        107
Daisy          106
Lucy            94
Buddy           87
Princess        86
Rocky           85
Luna            68
Jack            66
Lola            61
Sadie           58
Molly           57
Shadow          57
Maggie          55
Coco            55
Chico           54
Lily            53
Oreo            53
Blue            52
Lucky           51
Toby            50
Cookie          48
Ginger          48
Lady            47
Sam             46
Duke            45
Milo            44
Oliver          44
Sophie          44
              ...
Lady J           1
Nemesis          1
Corral           1
Big Ben          1
Thomasina        1
Moscato          1
Churley          1
Jeb              1
Baily            1
Boom             1
Jed              1
Home Girl        1
Hennesy          1
Jolli            1
Tabo             1
Butterball       1
Huitzi           1
Billy Bob        1
Guru Ramdas      1
Mr.Cookie        1
Tabs             1
Eedo             1
Marlyin          1
Meerkat          1
Tugga            1
Sally Jessy      1
Nelda            1
Hobie Cat        1
Madi             1
Sumi             1
Name: Name, dtype: int64

In [23]:
df.Name.mode()

0    Max
dtype: object

In [25]:
df.value_counts

AttributeError: 'DataFrame' object has no attribute 'value_counts'

In [29]:
df.DateTime

AnimalID
A671945    2014-02-12 18:22:00
A656520    2013-10-13 12:44:00
A686464    2015-01-31 12:28:00
A683430    2014-07-11 19:09:00
A667013    2013-11-15 12:52:00
A677334    2014-04-25 13:04:00
A699218    2015-03-28 13:11:00
A701489    2015-04-30 17:02:00
A671784    2014-02-04 17:17:00
A677747    2014-05-03 07:48:00
A668402    2013-12-05 15:50:00
A666320    2013-11-04 14:48:00
A684601    2016-02-03 11:27:00
A704702    2015-06-08 16:30:00
A688584    2015-11-25 15:00:00
A678825    2014-07-12 12:10:00
A678050    2014-05-03 16:15:00
A680028    2014-06-07 12:54:00
A679010    2014-05-17 11:32:00
A684787    2014-07-30 17:34:00
A670658    2014-01-19 15:03:00
A708812    2015-09-18 15:19:00
A705262    2015-08-15 14:22:00
A665781    2013-10-28 16:32:00
A676333    2014-04-09 17:44:00
A712750    2015-10-03 15:44:00
A718832    2016-01-15 17:31:00
A698777    2015-03-25 18:50:00
A715348    2015-11-21 13:01:00
A708666    2015-07-30 14:30:00
                  ...
A676460    2014-04-21 14:01:00
A704999    2015-06-15 19:28:00
A678842    2014-06-15 17:41:00
A713637    2015-10-11 09:42:00
A716670    2015-12-04 12:22:00
A716223    2015-11-17 17:17:00
A662498    2013-10-19 15:34:00
A689942    2014-10-19 13:29:00
A682690    2014-07-01 17:06:00
A666920    2013-11-13 17:32:00
A714386    2015-10-24 00:00:00
A692622    2014-11-24 17:21:00
A666284    2013-10-30 18:32:00
A535277    2015-04-20 16:04:00
A671169    2014-01-20 17:37:00
A679031    2014-05-31 16:11:00
A708833    2015-08-05 17:03:00
A697158    2015-05-02 21:04:00
A519949    2014-06-30 17:34:00
A701044    2015-04-28 14:26:00
A707871    2015-07-20 09:00:00
A704405    2015-07-18 14:08:00
A662019    2014-07-17 09:43:00
A687056    2014-08-31 09:00:00
A716997    2016-01-29 18:52:00
A702446    2015-05-14 11:56:00
A718934    2016-01-20 18:59:00
A698128    2015-03-09 13:33:00
A677478    2014-04-27 12:22:00
A706629    2015-07-02 09:00:00
Name: DateTime, dtype: object

In [31]:
df.DateTime.tail()

AnimalID
A702446    2015-05-14 11:56:00
A718934    2016-01-20 18:59:00
A698128    2015-03-09 13:33:00
A677478    2014-04-27 12:22:00
A706629    2015-07-02 09:00:00
Name: DateTime, dtype: object

In [32]:
df.DateTime[-1]

'2015-07-02 09:00:00'

In [33]:
type(df.DateTime[-1])
#this tells how difficult this will be to calculate from.

str

In [34]:
a = '2015-07-02 09:00:00'

In [35]:
b = pd.to_datetime(a)

In [36]:
b

Timestamp('2015-07-02 09:00:00')

In [38]:
b.year

2015

In [39]:
b.month

7

In [40]:
b.day

2

In [45]:
df.DateTime = pd.to_datetime(df.DateTime)
#Here we overwrote the date time - this is okay because it's the same data and we don't want to be too repetative.
#Better to overwrite in this case so you don't have a mssive file at the end with excess columns.

In [46]:
df.DateTime

AnimalID
A671945   2014-02-12 18:22:00
A656520   2013-10-13 12:44:00
A686464   2015-01-31 12:28:00
A683430   2014-07-11 19:09:00
A667013   2013-11-15 12:52:00
A677334   2014-04-25 13:04:00
A699218   2015-03-28 13:11:00
A701489   2015-04-30 17:02:00
A671784   2014-02-04 17:17:00
A677747   2014-05-03 07:48:00
A668402   2013-12-05 15:50:00
A666320   2013-11-04 14:48:00
A684601   2016-02-03 11:27:00
A704702   2015-06-08 16:30:00
A688584   2015-11-25 15:00:00
A678825   2014-07-12 12:10:00
A678050   2014-05-03 16:15:00
A680028   2014-06-07 12:54:00
A679010   2014-05-17 11:32:00
A684787   2014-07-30 17:34:00
A670658   2014-01-19 15:03:00
A708812   2015-09-18 15:19:00
A705262   2015-08-15 14:22:00
A665781   2013-10-28 16:32:00
A676333   2014-04-09 17:44:00
A712750   2015-10-03 15:44:00
A718832   2016-01-15 17:31:00
A698777   2015-03-25 18:50:00
A715348   2015-11-21 13:01:00
A708666   2015-07-30 14:30:00
                  ...
A676460   2014-04-21 14:01:00
A704999   2015-06-15 19:28:00
A678842   2014-06-15 17:41:00
A713637   2015-10-11 09:42:00
A716670   2015-12-04 12:22:00
A716223   2015-11-17 17:17:00
A662498   2013-10-19 15:34:00
A689942   2014-10-19 13:29:00
A682690   2014-07-01 17:06:00
A666920   2013-11-13 17:32:00
A714386   2015-10-24 00:00:00
A692622   2014-11-24 17:21:00
A666284   2013-10-30 18:32:00
A535277   2015-04-20 16:04:00
A671169   2014-01-20 17:37:00
A679031   2014-05-31 16:11:00
A708833   2015-08-05 17:03:00
A697158   2015-05-02 21:04:00
A519949   2014-06-30 17:34:00
A701044   2015-04-28 14:26:00
A707871   2015-07-20 09:00:00
A704405   2015-07-18 14:08:00
A662019   2014-07-17 09:43:00
A687056   2014-08-31 09:00:00
A716997   2016-01-29 18:52:00
A702446   2015-05-14 11:56:00
A718934   2016-01-20 18:59:00
A698128   2015-03-09 13:33:00
A677478   2014-04-27 12:22:00
A706629   2015-07-02 09:00:00
Name: DateTime, dtype: datetime64[ns]

In [48]:
df.OutcomeType.unique()

array(['Return_to_owner', 'Euthanasia', 'Adoption', 'Transfer', 'Died'], dtype=object)

In [49]:
df.OutcomeType.value_counts()

Adoption           10769
Transfer            9422
Return_to_owner     4786
Euthanasia          1555
Died                 197
Name: OutcomeType, dtype: int64

In [50]:
df.OutcomeSubtype.unique()

array([nan, 'Suffering', 'Foster', 'Partner', 'Offsite', 'SCRP',
       'Aggressive', 'Behavior', 'Rabies Risk', 'Medical', 'In Kennel',
       'In Foster', 'Barn', 'Court/Investigation', 'Enroute', 'At Vet',
       'In Surgery'], dtype=object)

In [51]:
pd.crosstab(df.OutcomeSubtype, df.OutcomeType)

OutcomeType          Adoption  Died  Euthanasia  Transfer
OutcomeSubtype
Aggressive                  0     0         320         0
At Vet                      0     4           0         0
Barn                        1     0           0         1
Behavior                    0     0          86         0
Court/Investigation         0     0           6         0
Enroute                     0     8           0         0
Foster                   1800     0           0         0
In Foster                   0    52           0         0
In Kennel                   0   114           0         0
In Surgery                  0     3           0         0
Medical                     0     0          66         0
Offsite                   165     0           0         0
Partner                     0     0           0      7816
Rabies Risk                 0     0          74         0
SCRP                        0     0           0      1599
Suffering                   0     0        1002         0

In [61]:
pd.crosstab(df.AnimalType, df.OutcomeType)

OutcomeType  Adoption  Died  Euthanasia  Return_to_owner  Transfer
AnimalType
Cat              4272   147         710              500      5505
Dog              6497    50         845             4286      3917

In [63]:
pd.crosstab(df.AnimalType, df.Name)

Name,Joanie,Mario,'Stache,007,3Buster,Aaron,Aaron Elvis,Abbadon,Abbey,Abbie,...,Zorro,Zsa-Zsa,Zu Zu,Zuchinni,Zues,Zuko,Zulma,Zulu,Zuzu,Zz
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN

In [70]:
df.query('AnimalType == "Dog" & (SexuponOutcome == "Spayed Female" | SexuponOutcome == "Intact Male")').Name.value_counts()

Bella           96
Daisy           79
Lucy            74
Princess        63
Lola            49
Luna            45
Sadie           42
Lady            38
Maggie          37
Coco            36
Molly           34
Roxy            32
Rosie           32
Sasha           31
Ginger          30
Cookie          29
Ruby            26
Diamond         26
Chloe           26
Zoey            25
Sophie          24
Lily            23
Bailey          23
Minnie          23
Stella          22
Gracie          21
Shadow          21
Honey           20
Charlie         20
Abby            19
                ..
Lois             1
Drusilla         1
Shaye            1
Aquiles          1
Gorda            1
Henney           1
Neko             1
Nicole           1
Bon Bon          1
Gertrude         1
Ares             1
Trini            1
Monkey           1
Kristy           1
Yo               1
Beagle           1
Dipper           1
Reesie           1
Chupitos         1
Boxochocolat     1
Prada            1
Cheetah          1
Lana Del Rey     1
Lovely           1
Josilyn          1
Christmas        1
Walter           1
Chucho           1
Emma Bella       1
Roxi             1
Name: Name, dtype: int64

In [71]:
df1 = df [df.AnimalType == 'Dog']

df2 = df1[(df1.SexuponOutcome == 'Intact Male') | (df1.SexuponOutcome == 'Neutered Male')]

In [88]:
d = {
'Neutered Male': True,
'Spayed Female': True, 
'Intact Male': False,
'Intact Female': False
}

df['Sterlized'] = df['SexuponOutcome'].map(d)

In [84]:
df

,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color,SexuponOutcomme
AnimalID,,,,,,,,,,
A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,True,1 year,Shetland Sheepdog Mix,Brown/White,True
A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,True,1 year,Domestic Shorthair Mix,Cream Tabby,True
A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,True,2 years,Pit Bull Mix,Blue/White,True
A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,False,3 weeks,Domestic Shorthair Mix,Blue Cream,False
A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,True,2 years,Lhasa Apso/Miniature Poodle,Tan,True
A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,False,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan,False
A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,False,3 weeks,Domestic Shorthair Mix,Blue Tabby,False
A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Brown Tabby,Unknown
A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,True,5 months,American Pit Bull Terrier Mix,Red/White,True
A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,True,1 year,Cairn Terrier,White,True
A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Black,Unknown
A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,True,2 years,Miniature Schnauzer Mix,Silver,True
A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,True,4 years,Pit Bull Mix,Brown,True
A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,True,2 years,Yorkshire Terrier Mix,Black/Red,True
A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,True,1 year,Great Pyrenees Mix,White/Cream,True
A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,True,3 months,Domestic Shorthair Mix,Orange Tabby/White,True
A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,False,3 weeks,Domestic Shorthair Mix,Brown Tabby,False
A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,False,2 weeks,Pit Bull Mix,Brown/White,False
A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,False,2 years,Angora Mix,White,False
A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,True,1 year,Flat Coat Retriever Mix,Black,True
A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,False,2 months,Queensland Heeler Mix,Black/White,False
A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,True,1 year,Domestic Shorthair Mix,White,True
A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,True,2 years,Plott Hound/Boxer,Brown Brindle/White,True
A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,True,10 months,German Shepherd Mix,Brown/White,True
A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,True,2 months,German Shepherd Mix,Black/Brown,True
A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,False,1 month,Domestic Shorthair Mix,Orange Tabby,False
A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,True,6 months,American Staffordshire Terrier Mix,Chocolate/White,True
A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,True,5 years,Chihuahua Shorthair Mix,White/Tan,True
A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,True,2 months,Domestic Shorthair Mix,Cream Tabby/White,True
A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,True,7 years,Russian Blue Mix,Blue,True
...,...,...,...,...,...,...,...,...,...,...
A676460,Mario,2014-04-21 14:01:00,Euthanasia,Behavior,Dog,True,2 years,American Pit Bull Terrier Mix,White/Black,True
A704999,Lion,2015-06-15 19:28:00,Return_to_owner,NaN,Dog,False,10 months,Great Pyrenees/Anatol Shepherd,Tan/Cream,False
A678842,Ella,2014-06-15 17:41:00,Transfer,Partner,Dog,False,11 months,Jack Russell Terrier Mix,White/Black,False
A713637,NaN,2015-10-11 09:42:00,Died,In Kennel,Cat,True,2 years,Siamese Mix,Lynx Point,True
A716670,Mowmow,2015-12-04 12:22:00,Transfer,Partner,Cat,True,6 years,Domestic Longhair Mix,Seal Point,True
A716223,Alice,2015-11-17 17:17:00,Transfer,Partner,Cat,False,4 weeks,Domestic Shorthair Mix,White/Black,False
A662498,Grace,2013-10-19 15:34:00,Transfer,Partner,Cat,False,2 months,Domestic Shorthair Mix,Tortie,False
A689942,Zoey,2014-10-19 13:29:00,Adoption,NaN,Cat,True,2 months,Domestic Shorthair Mix,Black,True
A682690,NaN,2014-07-01 17:06:00,Euthanasia,Suffering,Cat,Unknown,1 year,Domestic Shorthair Mix,Brown Tabby,Unknown
A666920,Herbie,2013-11-13 17:32:00,Transfer,Partner,Dog,True,2 years,Chihuahua Shorthair Mix,White/Brown,True
A714386,NaN,2015-10-24 00:00:00,Adoption,NaN,Dog,True,1 month,Chihuahua Shorthair Mix,Sable/Buff,True
A692622,Bonnie,2014-11-24 17:21:00,Transfer,Partner,Dog,False,1 month,Chihuahua Shorthair/Yorkshire Terrier,Brown/Black,False
A666284,Sonja,2013-10-30 18:32:00,Transfer,Partner,Dog,False,1 year,Cocker Spaniel/Dachshund,Buff,False
A535277,Merlin,2015-04-20 16:04:00,Return_to_owner,NaN,Dog,True,12 years,Rat Terrier,Chocolate/Tan,True
A671169,NaN,2014-01-20 17:37:00,Euthanasia,Suffering,Cat,False,18 years,Domestic Longhair Mix,Tortie,False
A679031,Pete,2014-05-31 16:11:00,Adoption,NaN,Cat,True,2 months,Domestic Shorthair Mix,Orange Tabby,True
A708833,Luna,2015-08-05 17:03:00,Adoption,NaN,Dog,True,2 months,Pointer Mix,Black/White,True
A697158,Max,2015-05-02 21:04:00,Adoption,Offsite,Dog,True,2 months,Newfoundland Mix,White/Black,True
A519949,Bella,2014-06-30 17:34:00,Return_to_owner,NaN,Dog,True,9 years,Bullmastiff Mix,Black,True
A701044,NaN,2015-04-28 14:26:00,Adoption,NaN,Dog,True,2 months,Siberian Husky/German Shepherd,Black/Tricolor,True
A707871,NaN,2015-07-20 09:00:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Brown Tabby/White,Unknown
A704405,Brownie,2015-07-18 14:08:00,Adoption,NaN,Cat,True,2 months,Domestic Shorthair Mix,Brown Tabby,True
A662019,Green Bean,2014-07-17 09:43:00,Adoption,Foster,Cat,True,5 years,Domestic Shorthair Mix,Black,True
A687056,NaN,2014-08-31 09:00:00,Transfer,SCRP,Cat,False,5 months,Domestic Shorthair Mix,Orange Tabby,False
A716997,Zeus,2016-01-29 18:52:00,Adoption,NaN,Dog,True,6 years,Staffordshire Mix,Blue/White,True
A702446,NaN,2015-05-14 11:56:00,Transfer,Partner,Cat,False,1 month,Domestic Shorthair Mix,Brown Tabby/White,False
A718934,NaN,2016-01-20 18:59:00,Transfer,SCRP,Cat,True,3 months,Domestic Shorthair Mix,Brown Tabby,True
A698128,Zeus,2015-03-09 13:33:00,Adoption,NaN,Dog,True,4 years,Old English Bulldog Mix,White/Tan,True
A677478,NaN,2014-04-27 12:22:00,Transfer,Partner,Cat,False,4 weeks,Domestic Shorthair Mix,Black,False
A706629,NaN,2015-07-02 09:00:00,Transfer,SCRP,Cat,False,1 year,Domestic Shorthair Mix,Brown Tabby/White,False

In [89]:
e = {
'Neutered Male'= True,
'Intact Male'= True,
'Spayed Female'= False,
'Intact Female'= False
}
df['Sterilized'] = df['SexuponOutcome'].replace(e)

SyntaxError: invalid syntax (<ipython-input-89-070422317cb7>, line 2)

In [90]:
df

,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color,SexuponOutcomme
AnimalID,,,,,,,,,,
A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,NaN,1 year,Shetland Sheepdog Mix,Brown/White,True
A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,NaN,1 year,Domestic Shorthair Mix,Cream Tabby,True
A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,NaN,2 years,Pit Bull Mix,Blue/White,True
A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,NaN,3 weeks,Domestic Shorthair Mix,Blue Cream,False
A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,NaN,2 years,Lhasa Apso/Miniature Poodle,Tan,True
A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,NaN,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan,False
A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,NaN,3 weeks,Domestic Shorthair Mix,Blue Tabby,False
A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,NaN,3 weeks,Domestic Shorthair Mix,Brown Tabby,Unknown
A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,NaN,5 months,American Pit Bull Terrier Mix,Red/White,True
A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,NaN,1 year,Cairn Terrier,White,True
A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,NaN,2 years,Domestic Shorthair Mix,Black,Unknown
A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,NaN,2 years,Miniature Schnauzer Mix,Silver,True
A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,NaN,4 years,Pit Bull Mix,Brown,True
A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,NaN,2 years,Yorkshire Terrier Mix,Black/Red,True
A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,NaN,1 year,Great Pyrenees Mix,White/Cream,True
A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,NaN,3 months,Domestic Shorthair Mix,Orange Tabby/White,True
A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,NaN,3 weeks,Domestic Shorthair Mix,Brown Tabby,False
A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,NaN,2 weeks,Pit Bull Mix,Brown/White,False
A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,NaN,2 years,Angora Mix,White,False
A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,NaN,1 year,Flat Coat Retriever Mix,Black,True
A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,NaN,2 months,Queensland Heeler Mix,Black/White,False
A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,NaN,1 year,Domestic Shorthair Mix,White,True
A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,NaN,2 years,Plott Hound/Boxer,Brown Brindle/White,True
A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,NaN,10 months,German Shepherd Mix,Brown/White,True
A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,NaN,2 months,German Shepherd Mix,Black/Brown,True
A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,NaN,1 month,Domestic Shorthair Mix,Orange Tabby,False
A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,NaN,6 months,American Staffordshire Terrier Mix,Chocolate/White,True
A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,NaN,5 years,Chihuahua Shorthair Mix,White/Tan,True
A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,NaN,2 months,Domestic Shorthair Mix,Cream Tabby/White,True
A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,NaN,7 years,Russian Blue Mix,Blue,True
...,...,...,...,...,...,...,...,...,...,...
A676460,Mario,2014-04-21 14:01:00,Euthanasia,Behavior,Dog,NaN,2 years,American Pit Bull Terrier Mix,White/Black,True
A704999,Lion,2015-06-15 19:28:00,Return_to_owner,NaN,Dog,NaN,10 months,Great Pyrenees/Anatol Shepherd,Tan/Cream,False
A678842,Ella,2014-06-15 17:41:00,Transfer,Partner,Dog,NaN,11 months,Jack Russell Terrier Mix,White/Black,False
A713637,NaN,2015-10-11 09:42:00,Died,In Kennel,Cat,NaN,2 years,Siamese Mix,Lynx Point,True
A716670,Mowmow,2015-12-04 12:22:00,Transfer,Partner,Cat,NaN,6 years,Domestic Longhair Mix,Seal Point,True
A716223,Alice,2015-11-17 17:17:00,Transfer,Partner,Cat,NaN,4 weeks,Domestic Shorthair Mix,White/Black,False
A662498,Grace,2013-10-19 15:34:00,Transfer,Partner,Cat,NaN,2 months,Domestic Shorthair Mix,Tortie,False
A689942,Zoey,2014-10-19 13:29:00,Adoption,NaN,Cat,NaN,2 months,Domestic Shorthair Mix,Black,True
A682690,NaN,2014-07-01 17:06:00,Euthanasia,Suffering,Cat,NaN,1 year,Domestic Shorthair Mix,Brown Tabby,Unknown
A666920,Herbie,2013-11-13 17:32:00,Transfer,Partner,Dog,NaN,2 years,Chihuahua Shorthair Mix,White/Brown,True
A714386,NaN,2015-10-24 00:00:00,Adoption,NaN,Dog,NaN,1 month,Chihuahua Shorthair Mix,Sable/Buff,True
A692622,Bonnie,2014-11-24 17:21:00,Transfer,Partner,Dog,NaN,1 month,Chihuahua Shorthair/Yorkshire Terrier,Brown/Black,False
A666284,Sonja,2013-10-30 18:32:00,Transfer,Partner,Dog,NaN,1 year,Cocker Spaniel/Dachshund,Buff,False
A535277,Merlin,2015-04-20 16:04:00,Return_to_owner,NaN,Dog,NaN,12 years,Rat Terrier,Chocolate/Tan,True
A671169,NaN,2014-01-20 17:37:00,Euthanasia,Suffering,Cat,NaN,18 years,Domestic Longhair Mix,Tortie,False
A679031,Pete,2014-05-31 16:11:00,Adoption,NaN,Cat,NaN,2 months,Domestic Shorthair Mix,Orange Tabby,True
A708833,Luna,2015-08-05 17:03:00,Adoption,NaN,Dog,NaN,2 months,Pointer Mix,Black/White,True
A697158,Max,2015-05-02 21:04:00,Adoption,Offsite,Dog,NaN,2 months,Newfoundland Mix,White/Black,True
A519949,Bella,2014-06-30 17:34:00,Return_to_owner,NaN,Dog,NaN,9 years,Bullmastiff Mix,Black,True
A701044,NaN,2015-04-28 14:26:00,Adoption,NaN,Dog,NaN,2 months,Siberian Husky/German Shepherd,Black/Tricolor,True
A707871,NaN,2015-07-20 09:00:00,Transfer,SCRP,Cat,NaN,2 years,Domestic Shorthair Mix,Brown Tabby/White,Unknown
A704405,Brownie,2015-07-18 14:08:00,Adoption,NaN,Cat,NaN,2 months,Domestic Shorthair Mix,Brown Tabby,True
A662019,Green Bean,2014-07-17 09:43:00,Adoption,Foster,Cat,NaN,5 years,Domestic Shorthair Mix,Black,True
A687056,NaN,2014-08-31 09:00:00,Transfer,SCRP,Cat,NaN,5 months,Domestic Shorthair Mix,Orange Tabby,False
A716997,Zeus,2016-01-29 18:52:00,Adoption,NaN,Dog,NaN,6 years,Staffordshire Mix,Blue/White,True
A702446,NaN,2015-05-14 11:56:00,Transfer,Partner,Cat,NaN,1 month,Domestic Shorthair Mix,Brown Tabby/White,False
A718934,NaN,2016-01-20 18:59:00,Transfer,SCRP,Cat,NaN,3 months,Domestic Shorthair Mix,Brown Tabby,True
A698128,Zeus,2015-03-09 13:33:00,Adoption,NaN,Dog,NaN,4 years,Old English Bulldog Mix,White/Tan,True
A677478,NaN,2014-04-27 12:22:00,Transfer,Partner,Cat,NaN,4 weeks,Domestic Shorthair Mix,Black,False
A706629,NaN,2015-07-02 09:00:00,Transfer,SCRP,Cat,NaN,1 year,Domestic Shorthair Mix,Brown Tabby/White,False

In [91]:
df.OutcomeType.unique()

array(['Return_to_owner', 'Euthanasia', 'Adoption', 'Transfer', 'Died'], dtype=object)

In [92]:
df['OutcomeType2'] = df.OutcomeType.apply(lambda outcome: 'ReturnToOwner' if outcome == 'Return_to_owner' else outcome)
# .apply is a shortcut function.

In [93]:
df['OutcomeType2'].value_counts()

Adoption         10769
Transfer          9422
ReturnToOwner     4786
Euthanasia        1555
Died               197
Name: OutcomeType2, dtype: int64

In [94]:
def my_outcome(outcome):
    if outcome == 'Return_to_owner':
        return 'ReturnToOwner'
    else:
        return outcome 
df['OutcomeType3'] = df.OutcomeType.apply(my_outcome)

In [95]:
df['OutcomeType3'].value_counts()

Adoption         10769
Transfer          9422
ReturnToOwner     4786
Euthanasia        1555
Died               197
Name: OutcomeType3, dtype: int64

In [96]:
df.SexuponOutcome.unique()

array([nan], dtype=object)

In [100]:
def my_sex(sex): 
    if sex == 'Neutered Male': 
        return 'Male'
    elif sex == 'Intact Male': 
        return 'Male'
    elif sex == 'Spayed Female':
        return 'Female'
    elif sex == 'Intact Female':
        return 'Female'
    else:
        return sex

In [102]:
'Male' in 'Neutered Male'

True

In [103]:
'male' in 'Intact Female'

True

In [105]:
def my_sex(sex): 
    if 'Male' in sex:
        return 'Male'
    elif 'Female' in sex: 
        return 'Female'
    else: 
        return np.nan
#what to do with NaN and Unknown...first question whether or not they are the same thing and combine if you can.

In [106]:
df.AgeuponOutcome.unique()

array(['1 year', '2 years', '3 weeks', '1 month', '5 months', '4 years',
       '3 months', '2 weeks', '2 months', '10 months', '6 months',
       '5 years', '7 years', '3 years', '4 months', '12 years', '9 years',
       '6 years', '1 weeks', '11 years', '4 weeks', '7 months', '8 years',
       '11 months', '4 days', '9 months', '8 months', '15 years',
       '10 years', '1 week', '0 years', '14 years', '3 days', '6 days',
       '5 days', '5 weeks', '2 days', '16 years', '1 day', '13 years', nan,
       '17 years', '18 years', '19 years', '20 years'], dtype=object)

In [107]:


df age_weeks(AgeuponOutcome):
    if year in AgeuponOutcome: 
        return float(AgeuponOutcome)
    elif month in AgeuponOutcome:
        return float(AgeuponOutcome)/12
    elif week in AgeuponOutcome:
        return AgeuponOutcome.float()/52
    elif day in AgeuponOutcome:
        return AgeuponOutcome.float()/362
    else:
        return np.nan

SyntaxError: invalid syntax (<ipython-input-107-700ada1a91e2>, line 1)

In [108]:
a = '1 year'
a.split()

['1', 'year']

In [109]:
(number,unit) = a.split()

In [112]:
number = float(number)

1.0

In [113]:
def my_age(age): 
    (value,unit) = age.split('')
    value = float(value)
    if ((unit == "day") | (unit == "days")):
        return value
    elif ((unit == "month") | (unit == "weeks"))
        return value * 7 
    elif 'month' in unit: 
        return value * 30.5

SyntaxError: invalid syntax (<ipython-input-113-d1a232d83670>, line 6)

In [114]:
df.Breed.unique()

array(['Shetland Sheepdog Mix', 'Domestic Shorthair Mix', 'Pit Bull Mix',
       ..., 'Vizsla/Boxer', 'German Shepherd/Australian Kelpie',
       'Boxer/German Shepherd'], dtype=object)